
import { PopularSite } from './types';

export const MIN_YEAR = 1995;
export const MAX_YEAR = 2026;

export const POPULAR_SITES: PopularSite[] = [
  { id: 'google', name: 'Google', url: 'google.com', icon: '🔍', startYear: 1998 },
  { id: 'apple', name: 'Apple', url: 'apple.com', icon: '🍎', startYear: 1996 },
  { id: 'amazon', name: 'Amazon', url: 'amazon.com', icon: '📦', startYear: 1995 },
  { id: 'facebook', name: 'Facebook', url: 'facebook.com', icon: '💙', startYear: 2004 },
  { id: 'youtube', name: 'YouTube', url: 'youtube.com', icon: '📺', startYear: 2005 },
  { id: 'nyt', name: 'NY Times', url: 'nytimes.com', icon: '📰', startYear: 1996 },
  { id: 'netflix', name: 'Netflix', url: 'netflix.com', icon: '🍿', startYear: 1997 },
  { id: 'yahoo', name: 'Yahoo', url: 'yahoo.com', icon: '🟣', startYear: 1995 },
  { id: 'wikipedia', name: 'Wikipedia', url: 'wikipedia.org', icon: '🌐', startYear: 2001 },
  { id: 'ebay', name: 'eBay', url: 'ebay.com', icon: '💰', startYear: 1995 },
];

export const ALL_POPULAR_SITES: PopularSite[] = [
  ...POPULAR_SITES,
  { id: 'microsoft', name: 'Microsoft', url: 'microsoft.com', icon: '💻', startYear: 1995 },
  { id: 'x', name: 'X', url: 'x.com', icon: '🗣️', startYear: 2006 },
  { id: 'linkedin', name: 'LinkedIn', url: 'linkedin.com', icon: '💼', startYear: 2003 },
  { id: 'pinterest', name: 'Pinterest', url: 'pinterest.com', icon: '📌', startYear: 2010 },
  { id: 'instagram', name: 'Instagram', url: 'instagram.com', icon: '📸', startYear: 2010 },
  { id: 'whatsapp', name: 'WhatsApp', url: 'whatsapp.com', icon: '💬', startYear: 2009 },
  { id: 'reddit', name: 'Reddit', url: 'reddit.com', icon: '👾', startYear: 2005 },
  { id: 'baidu', name: 'Baidu', url: 'baidu.com', icon: '🇨🇳', startYear: 2000 },
  { id: 'vk', name: 'VK', url: 'vk.com', icon: '🇷🇺', startYear: 2006 },
  { id: 'twitch', name: 'Twitch', url: 'twitch.tv', icon: '🎮', startYear: 2011 },
  { id: 'spotify', name: 'Spotify', url: 'spotify.com', icon: '🎵', startYear: 2006 },
  { id: 'discord', name: 'Discord', url: 'discord.com', icon: '🔊', startYear: 2015 },
  { id: 'github', name: 'GitHub', url: 'github.com', icon: '🐙', startYear: 2008 },
  { id: 'stackoverflow', name: 'Stack Overflow', url: 'stackoverflow.com', icon: '📚', startYear: 2008 },
  { id: 'wordpress', name: 'WordPress', url: 'wordpress.org', icon: '📝', startYear: 2003 },
  { id: 'imgur', name: 'Imgur', url: 'imgur.com', icon: '🖼️', startYear: 2007 },
  { id: 'tumblr', name: 'Tumblr', url: 'tumblr.com', icon: '✍️', startYear: 2007 },
  { id: 'blogger', name: 'Blogger', url: 'blogger.com', icon: '📰', startYear: 1999 },
  { id: 'flickr', name: 'Flickr', url: 'flickr.com', icon: '📸', startYear: 2004 },
  { id: 'deviantart', name: 'DeviantArt', url: 'deviantart.com', icon: '🎨', startYear: 2000 },
  { id: 'behance', name: 'Behance', url: 'behance.net', icon: '🖌️', startYear: 2006 },
  { id: 'dribbble', name: 'Dribbble', url: 'dribbble.com', icon: '🏀', startYear: 2009 },
  { id: 'medium', name: 'Medium', url: 'medium.com', icon: '📖', startYear: 2012 },
  { id: 'quora', name: 'Quora', url: 'quora.com', icon: '❓', startYear: 2009 },
  { id: 'askfm', name: 'Ask.fm', url: 'ask.fm', icon: '💬', startYear: 2010 },
  { id: 'slideshare', name: 'SlideShare', url: 'slideshare.net', icon: '📊', startYear: 2006 },
  { id: 'scribd', name: 'Scribd', url: 'scribd.com', icon: '📚', startYear: 2007 },
  { id: 'archiveorg', name: 'Internet Archive', url: 'archive.org', icon: '🏛️', startYear: 1996 },
  { id: 'etsy', name: 'Etsy', url: 'etsy.com', icon: '🛍️', startYear: 2005 },
  { id: 'shopify', name: 'Shopify', url: 'shopify.com', icon: '🛒', startYear: 2006 },
  { id: 'squarespace', name: 'Squarespace', url: 'squarespace.com', icon: '🌐', startYear: 2003 },
  { id: 'wix', name: 'Wix', url: 'wix.com', icon: '🛠️', startYear: 2006 },
  { id: 'zoom', name: 'Zoom', url: 'zoom.us', icon: '📞', startYear: 2011 },
  { id: 'webex', name: 'Webex', url: 'webex.com', icon: '💻', startYear: 1995 },
  { id: 'skype', name: 'Skype', url: 'skype.com', icon: '💬', startYear: 2003 },
  { id: 'slack', name: 'Slack', url: 'slack.com', icon: '🗨️', startYear: 2013 },
  { id: 'trello', name: 'Trello', url: 'trello.com', icon: '📋', startYear: 2011 },
  { id: 'asana', name: 'Asana', url: 'asana.com', icon: '✅', startYear: 2008 },
  { id: 'jira', name: 'Jira', url: 'atlassian.com/software/jira', icon: '⚙️', startYear: 2002 },
  { id: 'confluence', name: 'Confluence', url: 'atlassian.com/software/confluence', icon: '🤝', startYear: 2004 },
  { id: 'salesforce', name: 'Salesforce', url: 'salesforce.com', icon: '☁️', startYear: 1999 },
  { id: 'oracle', name: 'Oracle', url: 'oracle.com', icon: '💿', startYear: 1995 },
  { id: 'sap', name: 'SAP', url: 'sap.com', icon: '📈', startYear: 1996 },
  { id: 'ibm', name: 'IBM', url: 'ibm.com', icon: '🌐', startYear: 1995 },
  { id: 'hp', name: 'HP', url: 'hp.com', icon: '🖥️', startYear: 1995 },
  { id: 'dell', name: 'Dell', url: 'dell.com', icon: '💻', startYear: 1996 },
  { id: 'intel', name: 'Intel', url: 'intel.com', icon: '💡', startYear: 1995 },
  { id: 'nvidia', name: 'NVIDIA', url: 'nvidia.com', icon: '🎮', startYear: 1999 },
  { id: 'amd', name: 'AMD', url: 'amd.com', icon: '💻', startYear: 1996 },
  { id: 'qualcomm', name: 'Qualcomm', url: 'qualcomm.com', icon: '📱', startYear: 1995 },
  { id: 'broadcom', name: 'Broadcom', url: 'broadcom.com', icon: '📡', startYear: 1995 },
  { id: 'cisco', name: 'Cisco', url: 'cisco.com', icon: '🌐', startYear: 1995 },
  { id: 'huawei', name: 'Huawei', url: 'huawei.com', icon: '🇨🇳', startYear: 1995 },
  { id: 'samsung', name: 'Samsung', url: 'samsung.com', icon: '📱', startYear: 1995 },
  { id: 'lg', name: 'LG', url: 'lg.com', icon: '📺', startYear: 1995 },
  { id: 'sony', name: 'Sony', url: 'sony.com', icon: '🎧', startYear: 1995 },
  { id: 'panasonic', name: 'Panasonic', url: 'panasonic.com', icon: '🔋', startYear: 1995 },
  { id: 'toshiba', name: 'Toshiba', url: 'toshiba.com', icon: '💾', startYear: 1995 },
  { id: 'hitachi', name: 'Hitachi', url: 'hitachi.com', icon: '⚙️', startYear: 1995 },
  { id: 'mitsubishi', name: 'Mitsubishi', url: 'mitsubishicorp.com', icon: '🚗', startYear: 1995 },
  { id: 'honda', name: 'Honda', url: 'honda.com', icon: '🚗', startYear: 1995 },
  { id: 'toyota', name: 'Toyota', url: 'toyota.com', icon: '🚗', startYear: 1995 },
  { id: 'nissan', name: 'Nissan', url: 'nissan.com', icon: '🚗', startYear: 1995 },
  { id: 'ford', name: 'Ford', url: 'ford.com', icon: '🚗', startYear: 1995 },
  { id: 'gm', name: 'GM', url: 'gm.com', icon: '🚗', startYear: 1995 },
  { id: 'tesla', name: 'Tesla', url: 'tesla.com', icon: '🚗', startYear: 2003 },
  { id: 'bmw', name: 'BMW', url: 'bmw.com', icon: '🚗', startYear: 1995 },
  { id: 'mercedes', name: 'Mercedes-Benz', url: 'mercedes-benz.com', icon: '🚗', startYear: 1995 },
  { id: 'volkswagen', name: 'Volkswagen', url: 'vw.com', icon: '🚗', startYear: 1995 },
  { id: 'audi', name: 'Audi', url: 'audi.com', icon: '🚗', startYear: 1995 },
  { id: 'porsche', name: 'Porsche', url: 'porsche.com', icon: '🚗', startYear: 1995 },
  { id: 'ferrari', name: 'Ferrari', url: 'ferrari.com', icon: '🏎️', startYear: 1995 },
  { id: 'lamborghini', name: 'Lamborghini', url: 'lamborghini.com', icon: '🏎️', startYear: 1995 },
  { id: 'mcdonalds', name: 'McDonald\'s', url: 'mcdonalds.com', icon: '🍔', startYear: 1995 },
  { id: 'starbucks', name: 'Starbucks', url: 'starbucks.com', icon: '☕', startYear: 1995 },
  { id: 'cocacola', name: 'Coca-Cola', url: 'coca-cola.com', icon: '🥤', startYear: 1995 },
  { id: 'pepsi', name: 'Pepsi', url: 'pepsi.com', icon: '🥤', startYear: 1995 },
  { id: 'nike', name: 'Nike', url: 'nike.com', icon: '👟', startYear: 1995 },
  { id: 'adidas', name: 'Adidas', url: 'adidas.com', icon: '👟', startYear: 1995 },
  { id: 'zara', name: 'Zara', url: 'zara.com', icon: '👕', startYear: 1995 },
  { id: 'hm', name: 'H&M', url: 'hm.com', icon: '👚', startYear: 1998 },
  { id: 'ikea', name: 'IKEA', url: 'ikea.com', icon: '🛋️', startYear: 1995 },
  { id: 'samsungnews', name: 'Samsung Newsroom', url: 'news.samsung.com', icon: '📰', startYear: 2000 },
  { id: 'verizon', name: 'Verizon', url: 'verizon.com', icon: '📞', startYear: 1995 },
  { id: 'att', name: 'AT&T', url: 'att.com', icon: '📞', startYear: 1995 },
  { id: 'tmobile', name: 'T-Mobile', url: 't-mobile.com', icon: '📞', startYear: 1999 },
  { id: 'spacex', name: 'SpaceX', url: 'spacex.com', icon: '🚀', startYear: 2002 },
  { id: 'nasa', name: 'NASA', url: 'nasa.gov', icon: '🚀', startYear: 1995 },
  { id: 'un', name: 'United Nations', url: 'un.org', icon: '🇺🇳', startYear: 1995 },
  { id: 'who', name: 'WHO', url: 'who.int', icon: '⚕️', startYear: 1995 },
  { id: 'redcross', name: 'Red Cross', url: 'redcross.org', icon: '🏥', startYear: 1995 },
  { id: 'wikipediaes', name: 'Wikipedia (ES)', url: 'es.wikipedia.org', icon: '🌐', startYear: 2001 },
  { id: 'googlescholar', name: 'Google Scholar', url: 'scholar.google.com', icon: '🎓', startYear: 2004 },
  { id: 'arstechnica', name: 'Ars Technica', url: 'arstechnica.com', icon: '🖥️', startYear: 1998 },
  { id: 'techcrunch', name: 'TechCrunch', url: 'techcrunch.com', icon: '💰', startYear: 2005 },
  { id: 'theverge', name: 'The Verge', url: 'theverge.com', icon: '📱', startYear: 2011 },
  { id: 'mashable', name: 'Mashable', url: 'mashable.com', icon: '📰', startYear: 2005 },
  { id: 'engadget', name: 'Engadget', url: 'engadget.com', icon: ' Gadget', startYear: 2004 },
  { id: 'wired', name: 'Wired', url: 'wired.com', icon: '🔌', startYear: 1995 },
  { id: 'ign', name: 'IGN', url: 'ign.com', icon: '🎮', startYear: 1996 },
  { id: 'gamespot', name: 'GameSpot', url: 'gamespot.com', icon: '🎮', startYear: 1996 },
  { id: 'rottentomatoes', name: 'Rotten Tomatoes', url: 'rottentomatoes.com', icon: '🍅', startYear: 1998 },
  { id: 'imdb', name: 'IMDb', url: 'imdb.com', icon: '🎬', startYear: 1995 },
  { id: 'allrecipes', name: 'Allrecipes', url: 'allrecipes.com', icon: '🍳', startYear: 1997 },
  { id: 'foodnetwork', name: 'Food Network', url: 'foodnetwork.com', icon: '🍽️', startYear: 1996 },
  { id: 'epicurious', name: 'Epicurious', url: 'epicurious.com', icon: '🍇', startYear: 1995 },
  { id: 'webmd', name: 'WebMD', url: 'webmd.com', icon: '⚕️', startYear: 1996 },
  { id: 'mayoclinic', name: 'Mayo Clinic', url: 'mayoclinic.org', icon: '🏥', startYear: 1995 },
  { id: 'nih', name: 'NIH', url: 'nih.gov', icon: '🔬', startYear: 1995 },
  { id: 'cdc', name: 'CDC', url: 'cdc.gov', icon: '🦠', startYear: 1995 },
  { id: 'whois', name: 'WHOIS', url: 'whois.com', icon: '🌐', startYear: 1995 },
  { id: 'gravatar', name: 'Gravatar', url: 'gravatar.com', icon: '👤', startYear: 2007 },
  { id: 'unsplash', name: 'Unsplash', url: 'unsplash.com', icon: '📸', startYear: 2013 },
  { id: 'pexels', name: 'Pexels', url: 'pexels.com', icon: '📷', startYear: 2014 },
  { id: 'pixabay', name: 'Pixabay', url: 'pixabay.com', icon: '🖼️', startYear: 2010 },
  { id: 'fontsgoogle', name: 'Google Fonts', url: 'fonts.google.com', icon: '🅰️', startYear: 2010 },
  { id: 'fontawesome', name: 'Font Awesome', url: 'fontawesome.com', icon: '🌟', startYear: 2012 },
  { id: 'flaticon', name: 'Flaticon', url: 'flaticon.com', icon: '💡', startYear: 2013 },
  { id: 'thenounproject', name: 'The Noun Project', url: 'thenounproject.com', icon: '🔠', startYear: 2010 },
  { id: 'materialui', name: 'Material-UI', url: 'mui.com', icon: '⚛️', startYear: 2014 },
  { id: 'bootstrap', name: 'Bootstrap', url: 'getbootstrap.com', icon: '🅱️', startYear: 2011 },
  { id: 'tailwindcss', name: 'Tailwind CSS', url: 'tailwindcss.com', icon: '🌬️', startYear: 2017 },
  { id: 'reactjs', name: 'React', url: 'react.dev', icon: '⚛️', startYear: 2013 },
  { id: 'angularjs', name: 'Angular', url: 'angular.io', icon: '🅰️', startYear: 2010 },
  { id: 'vuejs', name: 'Vue.js', url: 'vuejs.org', icon: '💡', startYear: 2014 },
  { id: 'jquery', name: 'jQuery', url: 'jquery.com', icon: '⚡', startYear: 2006 },
  { id: 'nodejs', name: 'Node.js', url: 'nodejs.org', icon: '🟩', startYear: 2009 },
  { id: 'expressjs', name: 'Express.js', url: 'expressjs.com', icon: '🚂', startYear: 2010 },
  { id: 'djangoproject', name: 'Django', url: 'djangoproject.com', icon: '🐍', startYear: 2005 },
  { id: 'rubyonrails', name: 'Ruby on Rails', url: 'rubyonrails.org', icon: '💎', startYear: 2004 },
  { id: 'laravel', name: 'Laravel', url: 'laravel.com', icon: ' artisan', startYear: 2011 },
  { id: 'spring', name: 'Spring', url: 'spring.io', icon: '🍃', startYear: 2002 },
  { id: 'dotnet', name: '.NET', url: 'dotnet.microsoft.com', icon: '🌐', startYear: 2002 },
  { id: 'php', name: 'PHP', url: 'php.net', icon: '🐘', startYear: 1995 },
  { id: 'python', name: 'Python', url: 'python.org', icon: '🐍', startYear: 1995 },
  { id: 'java', name: 'Java', url: 'java.com', icon: '☕', startYear: 1995 },
  { id: 'cpp', name: 'C++', url: 'cplusplus.com', icon: '💻', startYear: 1995 },
  { id: 'swift', name: 'Swift', url: 'swift.org', icon: '🍎', startYear: 2014 },
  { id: 'kotlin', name: 'Kotlin', url: 'kotlinlang.org', icon: '⚙️', startYear: 2011 },
  { id: 'typescript', name: 'TypeScript', url: 'typescriptlang.org', icon: '🟦', startYear: 2012 },
  { id: 'golang', name: 'Go', url: 'go.dev', icon: '🐹', startYear: 2009 },
  { id: 'rustlang', name: 'Rust', url: 'rust-lang.org', icon: '🦀', startYear: 2010 },
  { id: 'haskell', name: 'Haskell', url: 'haskell.org', icon: 'λ', startYear: 1995 },
  { id: 'scala', name: 'Scala', url: 'scala-lang.org', icon: '📈', startYear: 2003 },
  { id: 'rstats', name: 'R', url: 'r-project.org', icon: '📊', startYear: 1995 },
  { id: 'matlab', name: 'MATLAB', url: 'mathworks.com/products/matlab', icon: '📉', startYear: 1995 },
  { id: 'jupyter', name: 'Jupyter', url: 'jupyter.org', icon: '💡', startYear: 2014 },
  { id: 'tensorflow', name: 'TensorFlow', url: 'tensorflow.org', icon: '🧠', startYear: 2015 },
  { id: 'pytorch', name: 'PyTorch', url: 'pytorch.org', icon: '💡', startYear: 2016 },
  { id: 'keras', name: 'Keras', url: 'keras.io', icon: '🧠', startYear: 2015 },
  { id: 'scikitlearn', name: 'Scikit-learn', url: 'scikit-learn.org', icon: '📊', startYear: 2007 },
  { id: 'pandas', name: 'Pandas', url: 'pandas.pydata.org', icon: '🐼', startYear: 2008 },
  { id: 'numpy', name: 'NumPy', url: 'numpy.org', icon: '🔢', startYear: 1995 },
  { id: 'docker', name: 'Docker', url: 'docker.com', icon: '🐳', startYear: 2013 },
  { id: 'kubernetes', name: 'Kubernetes', url: 'kubernetes.io', icon: '☸️', startYear: 2014 },
  { id: 'aws', name: 'AWS', url: 'aws.amazon.com', icon: '☁️', startYear: 2006 },
  { id: 'azure', name: 'Azure', url: 'azure.microsoft.com', icon: '☁️', startYear: 2010 },
  { id: 'gcp', name: 'Google Cloud', url: 'cloud.google.com', icon: '☁️', startYear: 2008 },
  { id: 'heroku', name: 'Heroku', url: 'heroku.com', icon: '☁️', startYear: 2007 },
  { id: 'netlify', name: 'Netlify', url: 'netlify.com', icon: '🌐', startYear: 2014 },
  { id: 'vercel', name: 'Vercel', url: 'vercel.com', icon: '▲', startYear: 2015 },
  { id: 'cloudflare', name: 'Cloudflare', url: 'cloudflare.com', icon: '☁️', startYear: 2009 },
  { id: 'githubpages', name: 'GitHub Pages', url: 'pages.github.com', icon: '🐙', startYear: 2008 },
  { id: 'gitlab', name: 'GitLab', url: 'gitlab.com', icon: '🦊', startYear: 2011 },
  { id: 'bitbucket', name: 'Bitbucket', url: 'bitbucket.org', icon: '‍', startYear: 2008 },
  { id: 'stackoverflowmeta', name: 'Stack Overflow Meta', url: 'meta.stackoverflow.com', icon: '📚', startYear: 2008 },
  { id: 'serverfault', name: 'Server Fault', url: 'serverfault.com', icon: '💻', startYear: 2009 },
  { id: 'superuser', name: 'Super User', url: 'superuser.com', icon: '💻', startYear: 2009 },
  { id: 'askubuntu', name: 'Ask Ubuntu', url: 'askubuntu.com', icon: '🐧', startYear: 2010 },
  { id: 'appledeveloper', name: 'Apple Developer', url: 'developer.apple.com', icon: '🍎', startYear: 1995 },
  { id: 'androiddeveloper', name: 'Android Developers', url: 'developer.android.com', icon: '🤖', startYear: 2007 },
  { id: 'mozilla', name: 'Mozilla', url: 'mozilla.org', icon: '🦊', startYear: 1998 },
  { id: 'w3c', name: 'W3C', url: 'w3.org', icon: '🌐', startYear: 1995 },
  { id: 'smashingmagazine', name: 'Smashing Magazine', url: 'smashingmagazine.com', icon: '📖', startYear: 2006 },
  { id: 'css-tricks', name: 'CSS-Tricks', url: 'css-tricks.com', icon: '🎨', startYear: 2007 },
  { id: 'sitepoint', name: 'SitePoint', url: 'sitepoint.com', icon: '📚', startYear: 1999 },
  { id: 'freecodecamp', name: 'freeCodeCamp', url: 'freecodecamp.org', icon: '🏕️', startYear: 2014 },
  { id: 'udemy', name: 'Udemy', url: 'udemy.com', icon: '🎓', startYear: 2010 },
  { id: 'coursera', name: 'Coursera', url: 'coursera.org', icon: '🎓', startYear: 2012 },
  { id: 'edx', name: 'edX', url: 'edx.org', icon: '🎓', startYear: 2012 },
  { id: 'khanacademy', name: 'Khan Academy', url: 'khanacademy.org', icon: '🏫', startYear: 2008 },
  { id: 'mediumblog', name: 'Medium Blog', url: 'blog.medium.com', icon: '📖', startYear: 2012 },
  { id: 'devto', name: 'DEV Community', url: 'dev.to', icon: '📝', startYear: 2016 },
  { id: 'hashnode', name: 'Hashnode', url: 'hashnode.com', icon: '📝', startYear: 2020 },
  { id: 'scotch_io', name: 'Scotch.io', url: 'scotch.io', icon: '🥃', startYear: 2013 },
  { id: 'tutorialspoint', name: 'TutorialsPoint', url: 'tutorialspoint.com', icon: '📚', startYear: 2006 },
  { id: 'geeksforgeeks', name: 'GeeksforGeeks', url: 'geeksforgeeks.org', icon: '🤓', startYear: 2007 },
  { id: 'programiz', name: 'Programiz', url: 'programiz.com', icon: '💻', startYear: 2012 },
  { id: 'codecademy', name: 'Codecademy', url: 'codecademy.com', icon: '🎓', startYear: 2011 },
  { id: 'hackerrank', name: 'HackerRank', url: 'hackerrank.com', icon: '💻', startYear: 2009 },
  { id: 'leetcode', name: 'LeetCode', url: 'leetcode.com', icon: '💻', startYear: 2011 },
  { id: 'topcoder', name: 'TopCoder', url: 'topcoder.com', icon: '🏆', startYear: 2001 },
  { id: 'codechef', name: 'CodeChef', url: 'codechef.com', icon: '👨‍🍳', startYear: 2009 },
  { id: 'codesignal', name: 'CodeSignal', url: 'codesignal.com', icon: '🚦', startYear: 2010 },
  { id: 'codewars', name: 'Codewars', url: 'codewars.com', icon: '🥋', startYear: 2012 },
  { id: 'projecteuler', name: 'Project Euler', url: 'projecteuler.net', icon: '🔢', startYear: 2001 },
  { id: 'kaggle', name: 'Kaggle', url: 'kaggle.com', icon: '📊', startYear: 2010 },
  { id: 'towardsdatascience', name: 'Towards Data Science', url: 'towardsdatascience.com', icon: '📈', startYear: 2016 },
];
