
import { PopularSite } from './types';

export const MIN_YEAR = 1995;
export const MAX_YEAR = 2026;

export const POPULAR_SITES: PopularSite[] = [
  { id: 'google', name: 'Google', url: 'google.com', icon: '🔍', startYear: 1998 },
  { id: 'apple', name: 'Apple', url: 'apple.com', icon: '🍎', startYear: 1996 },
  { id: 'amazon', name: 'Amazon', url: 'amazon.com', icon: '📦', startYear: 1995 },
  { id: 'youtube', name: 'YouTube', url: 'youtube.com', icon: '📺', startYear: 2005 },
  { id: 'nyt', name: 'NY Times', url: 'nytimes.com', icon: '📰', startYear: 1996 },
  { id: 'facebook', name: 'Facebook', url: 'facebook.com', icon: '💙', startYear: 2004 },
  { id: 'netflix', name: 'Netflix', url: 'netflix.com', icon: '🍿', startYear: 1997 },
  { id: 'yahoo', name: 'Yahoo', url: 'yahoo.com', icon: '🟣', startYear: 1995 },
  { id: 'wikipedia', name: 'Wikipedia', url: 'wikipedia.org', icon: '🌐', startYear: 2001 },
  { id: 'ebay', name: 'eBay', url: 'ebay.com', icon: '💰', startYear: 1995 },
];

export const ALL_POPULAR_SITES: PopularSite[] = [
  ...POPULAR_SITES,
  { id: 'microsoft', name: 'Microsoft', url: 'microsoft.com', icon: '💻', startYear: 1995 },
  { id: 'x', name: 'X', url: 'x.com', icon: '🗣️', startYear: 2006 },
  { id: 'linkedin', name: 'LinkedIn', url: 'linkedin.com', icon: '💼', startYear: 2003 },
  { id: 'pinterest', name: 'Pinterest', url: 'pinterest.com', icon: '📌', startYear: 2010 },
  { id: 'instagram', name: 'Instagram', url: 'instagram.com', icon: '📸', startYear: 2010 },
  { id: 'whatsapp', name: 'WhatsApp', url: 'whatsapp.com', icon: '💬', startYear: 2009 },
  { id: 'reddit', name: 'Reddit', url: 'reddit.com', icon: '👾', startYear: 2005 },
  { id: 'baidu', name: 'Baidu', url: 'baidu.com', icon: '🇨🇳', startYear: 2000 },
  { id: 'vk', name: 'VK', url: 'vk.com', icon: '🇷🇺', startYear: 2006 },
  { id: 'twitch', name: 'Twitch', url: 'twitch.tv', icon: '🎮', startYear: 2011 },
  { id: 'spotify', name: 'Spotify', url: 'spotify.com', icon: '🎵', startYear: 2006 },
  { id: 'discord', name: 'Discord', url: 'discord.com', icon: '🔊', startYear: 2015 },
  { id: 'github', name: 'GitHub', url: 'github.com', icon: '🐙', startYear: 2008 },
  { id: 'stackoverflow', name: 'Stack Overflow', url: 'stackoverflow.com', icon: '📚', startYear: 2008 },
  { id: 'wordpress', name: 'WordPress', url: 'wordpress.org', icon: '📝', startYear: 2003 },
  { id: 'imgur', name: 'Imgur', url: 'imgur.com', icon: '🖼️', startYear: 2007 },
  { id: 'tumblr', name: 'Tumblr', url: 'tumblr.com', icon: '✍️', startYear: 2007 },
  { id: 'blogger', name: 'Blogger', url: 'blogger.com', icon: '📰', startYear: 1999 },
  { id: 'flickr', name: 'Flickr', url: 'flickr.com', icon: '📸', startYear: 2004 },
  { id: 'deviantart', name: 'DeviantArt', url: 'deviantart.com', icon: '🎨', startYear: 2000 },
  { id: 'behance', name: 'Behance', url: 'behance.net', icon: '🖌️', startYear: 2006 },
  { id: 'dribbble', name: 'Dribbble', url: 'dribbble.com', icon: '🏀', startYear: 2009 },
  { id: 'medium', name: 'Medium', url: 'medium.com', icon: '📖', startYear: 2012 },
  { id: 'quora', name: 'Quora', url: 'quora.com', icon: '❓', startYear: 2009 },
  { id: 'askfm', name: 'Ask.fm', url: 'ask.fm', icon: '💬', startYear: 2010 },
  { id: 'slideshare', name: 'SlideShare', url: 'slideshare.net', icon: '📊', startYear: 2006 },
  { id: 'scribd', name: 'Scribd', url: 'scribd.com', icon: '📚', startYear: 2007 },
  { id: 'archiveorg', name: 'Internet Archive', url: 'archive.org', icon: '🏛️', startYear: 1996 },
  { id: 'etsy', name: 'Etsy', url: 'etsy.com', icon: '🛍️', startYear: 2005 },
  { id: 'shopify', name: 'Shopify', url: 'shopify.com', icon: '🛒', startYear: 2006 },
  { id: 'squarespace', name: 'Squarespace', url: 'squarespace.com', icon: '🌐', startYear: 2003 },
  { id: 'wix', name: 'Wix', url: 'wix.com', icon: '🛠️', startYear: 2006 },
  { id: 'zoom', name: 'Zoom', url: 'zoom.us', icon: '📞', startYear: 2011 },
  { id: 'webex', name: 'Webex', url: 'webex.com', icon: '💻', startYear: 1995 },
  { id: 'skype', name: 'Skype', url: 'skype.com', icon: '💬', startYear: 2003 },
  { id: 'slack', name: 'Slack', url: 'slack.com', icon: '🗨️', startYear: 2013 },
  { id: 'trello', name: 'Trello', url: 'trello.com', icon: '📋', startYear: 2011 },
  { id: 'asana', name: 'Asana', url: 'asana.com', icon: '✅', startYear: 2008 },
  { id: 'jira', name: 'Jira', url: 'atlassian.com/software/jira', icon: '⚙️', startYear: 2002 },
  { id: 'confluence', name: 'Confluence', url: 'atlassian.com/software/confluence', icon: '🤝', startYear: 2004 },
  { id: 'salesforce', name: 'Salesforce', url: 'salesforce.com', icon: '☁️', startYear: 1999 },
  { id: 'oracle', name: 'Oracle', url: 'oracle.com', icon: '💿', startYear: 1995 },
  { id: 'sap', name: 'SAP', url: 'sap.com', icon: '📈', startYear: 1996 },
  { id: 'ibm', name: 'IBM', url: 'ibm.com', icon: '🌐', startYear: 1995 },
  { id: 'hp', name: 'HP', url: 'hp.com', icon: '🖥️', startYear: 1995 },
  { id: 'dell', name: 'Dell', url: 'dell.com', icon: '💻', startYear: 1996 },
  { id: 'intel', name: 'Intel', url: 'intel.com', icon: '💡', startYear: 1995 },
  { id: 'nvidia', name: 'NVIDIA', url: 'nvidia.com', icon: '🎮', startYear: 1999 },
  { id: 'amd', name: 'AMD', url: 'amd.com', icon: '💻', startYear: 1996 },
  { id: 'qualcomm', name: 'Qualcomm', url: 'qualcomm.com', icon: '📱', startYear: 1995 },
  { id: 'broadcom', name: 'Broadcom', url: 'broadcom.com', icon: '📡', startYear: 1995 },
  { id: 'cisco', name: 'Cisco', url: 'cisco.com', icon: '🌐', startYear: 1995 },
  { id: 'huawei', name: 'Huawei', url: 'huawei.com', icon: '🇨🇳', startYear: 1995 },
  { id: 'samsung', name: 'Samsung', url: 'samsung.com', icon: '📱', startYear: 1995 },
  { id: 'lg', name: 'LG', url: 'lg.com', icon: '📺', startYear: 1995 },
  { id: 'sony', name: 'Sony', url: 'sony.com', icon: '🎧', startYear: 1995 },
  { id: 'panasonic', name: 'Panasonic', url: 'panasonic.com', icon: '🔋', startYear: 1995 },
  { id: 'toshiba', name: 'Toshiba', url: 'toshiba.com', icon: '💾', startYear: 1995 },
  { id: 'hitachi', name: 'Hitachi', url: 'hitachi.com', icon: '⚙️', startYear: 1995 },
  { id: 'mitsubishi', name: 'Mitsubishi', url: 'mitsubishicorp.com', icon: '🚗', startYear: 1995 },
  { id: 'honda', name: 'Honda', url: 'honda.com', icon: '🚗', startYear: 1995 },
  { id: 'toyota', name: 'Toyota', url: 'toyota.com', icon: '🚗', startYear: 1995 },
  { id: 'nissan', name: 'Nissan', url: 'nissan.com', icon: '🚗', startYear: 1995 },
  { id: 'ford', name: 'Ford', url: 'ford.com', icon: '🚗', startYear: 1995 },
  { id: 'gm', name: 'GM', url: 'gm.com', icon: '🚗', startYear: 1995 },
  { id: 'tesla', name: 'Tesla', url: 'tesla.com', icon: '🚗', startYear: 2003 },
  { id: 'bmw', name: 'BMW', url: 'bmw.com', icon: '🚗', startYear: 1995 },
  { id: 'mercedes', name: 'Mercedes-Benz', url: 'mercedes-benz.com', icon: '🚗', startYear: 1995 },
  { id: 'volkswagen', name: 'Volkswagen', url: 'vw.com', icon: '🚗', startYear: 1995 },
  { id: 'audi', name: 'Audi', url: 'audi.com', icon: '🚗', startYear: 1995 },
  { id: 'porsche', name: 'Porsche', url: 'porsche.com', icon: '🚗', startYear: 1995 },
  { id: 'ferrari', name: 'Ferrari', url: 'ferrari.com', icon: '🏎️', startYear: 1995 },
  { id: 'lamborghini', name: 'Lamborghini', url: 'lamborghini.com', icon: '🏎️', startYear: 1995 },
  { id: 'mcdonalds', name: 'McDonald\'s', url: 'mcdonalds.com', icon: '🍔', startYear: 1995 },
  { id: 'starbucks', name: 'Starbucks', url: 'starbucks.com', icon: '☕', startYear: 1995 },
  { id: 'cocacola', name: 'Coca-Cola', url: 'coca-cola.com', icon: '🥤', startYear: 1995 },
  { id: 'pepsi', name: 'Pepsi', url: 'pepsi.com', icon: '🥤', startYear: 1995 },
  { id: 'nike', name: 'Nike', url: 'nike.com', icon: '👟', startYear: 1995 },
  { id: 'adidas', name: 'Adidas', url: 'adidas.com', icon: '👟', startYear: 1995 },
  { id: 'zara', name: 'Zara', url: 'zara.com', icon: '👕', startYear: 1995 },
  { id: 'hm', name: 'H&M', url: 'hm.com', icon: '👚', startYear: 1998 },
  { id: 'ikea', name: 'IKEA', url: 'ikea.com', icon: '🛋️', startYear: 1995 },
  { id: 'samsungnews', name: 'Samsung Newsroom', url: 'news.samsung.com', icon: '📰', startYear: 2000 },
  { id: 'verizon', name: 'Verizon', url: 'verizon.com', icon: '📞', startYear: 1995 },
  { id: 'att', name: 'AT&T', url: 'att.com', icon: '📞', startYear: 1995 },
  { id: 'tmobile', name: 'T-Mobile', url: 't-mobile.com', icon: '📞', startYear: 1999 },
  { id: 'spacex', name: 'SpaceX', url: 'spacex.com', icon: '🚀', startYear: 2002 },
  { id: 'nasa', name: 'NASA', url: 'nasa.gov', icon: '🚀', startYear: 1995 },
  { id: 'un', name: 'United Nations', url: 'un.org', icon: '🇺🇳', startYear: 1995 },
  { id: 'who', name: 'WHO', url: 'who.int', icon: '⚕️', startYear: 1995 },
  { id: 'redcross', name: 'Red Cross', url: 'redcross.org', icon: '🏥', startYear: 1995 },
  { id: 'wikipediaes', name: 'Wikipedia (ES)', url: 'es.wikipedia.org', icon: '🌐', startYear: 2001 },
  { id: 'googlescholar', name: 'Google Scholar', url: 'scholar.google.com', icon: '🎓', startYear: 2004 },
  { id: 'arstechnica', name: 'Ars Technica', url: 'arstechnica.com', icon: '🖥️', startYear: 1998 },
  { id: 'techcrunch', name: 'TechCrunch', url: 'techcrunch.com', icon: '💰', startYear: 2005 },
  { id: 'theverge', name: 'The Verge', url: 'theverge.com', icon: '📱', startYear: 2011 },
  { id: 'mashable', name: 'Mashable', url: 'mashable.com', icon: '📰', startYear: 2005 },
  { id: 'engadget', name: 'Engadget', url: 'engadget.com', icon: ' Gadget', startYear: 2004 },
  { id: 'wired', name: 'Wired', url: 'wired.com', icon: '🔌', startYear: 1995 },
  { id: 'ign', name: 'IGN', url: 'ign.com', icon: '🎮', startYear: 1996 },
  { id: 'gamespot', name: 'GameSpot', url: 'gamespot.com', icon: '🎮', startYear: 1996 },
  { id: 'rottentomatoes', name: 'Rotten Tomatoes', url: 'rottentomatoes.com', icon: '🍅', startYear: 1998 },
  { id: 'imdb', name: 'IMDb', url: 'imdb.com', icon: '🎬', startYear: 1995 },
  { id: 'allrecipes', name: 'Allrecipes', url: 'allrecipes.com', icon: '🍳', startYear: 1997 },
  { id: 'foodnetwork', name: 'Food Network', url: 'foodnetwork.com', icon: '🍽️', startYear: 1996 },
  { id: 'epicurious', name: 'Epicurious', url: 'epicurious.com', icon: '🍇', startYear: 1995 },
  { id: 'webmd', name: 'WebMD', url: 'webmd.com', icon: '⚕️', startYear: 1996 },
  { id: 'mayoclinic', name: 'Mayo Clinic', url: 'mayoclinic.org', icon: '🏥', startYear: 1995 },
  { id: 'nih', name: 'NIH', url: 'nih.gov', icon: '🔬', startYear: 1995 },
  { id: 'cdc', name: 'CDC', url: 'cdc.gov', icon: '🦠', startYear: 1995 },
  { id: 'whois', name: 'WHOIS', url: 'whois.com', icon: '🌐', startYear: 1995 },
  { id: 'gravatar', name: 'Gravatar', url: 'gravatar.com', icon: '👤', startYear: 2007 },
  { id: 'unsplash', name: 'Unsplash', url: 'unsplash.com', icon: '📸', startYear: 2013 },
  { id: 'pexels', name: 'Pexels', url: 'pexels.com', icon: '📷', startYear: 2014 },
  { id: 'pixabay', name: 'Pixabay', url: 'pixabay.com', icon: '🖼️', startYear: 2010 },
  { id: 'fontsgoogle', name: 'Google Fonts', url: 'fonts.google.com', icon: '🅰️', startYear: 2010 },
  { id: 'fontawesome', name: 'Font Awesome', url: 'fontawesome.com', icon: '🌟', startYear: 2012 },
  { id: 'flaticon', name: 'Flaticon', url: 'flaticon.com', icon: '💡', startYear: 2013 },
  { id: 'thenounproject', name: 'The Noun Project', url: 'thenounproject.com', icon: '🔠', startYear: 2010 },
  { id: 'materialui', name: 'Material-UI', url: 'mui.com', icon: '⚛️', startYear: 2014 },
  { id: 'bootstrap', name: 'Bootstrap', url: 'getbootstrap.com', icon: '🅱️', startYear: 2011 },
  { id: 'tailwindcss', name: 'Tailwind CSS', url: 'tailwindcss.com', icon: '🌬️', startYear: 2017 },
  { id: 'reactjs', name: 'React', url: 'react.dev', icon: '⚛️', startYear: 2013 },
  { id: 'angularjs', name: 'Angular', url: 'angular.io', icon: '🅰️', startYear: 2010 },
  { id: 'vuejs', name: 'Vue.js', url: 'vuejs.org', icon: '💡', startYear: 2014 },
  { id: 'jquery', name: 'jQuery', url: 'jquery.com', icon: '⚡', startYear: 2006 },
  { id: 'nodejs', name: 'Node.js', url: 'nodejs.org', icon: '🟩', startYear: 2009 },
  { id: 'expressjs', name: 'Express.js', url: 'expressjs.com', icon: '🚂', startYear: 2010 },
  { id: 'djangoproject', name: 'Django', url: 'djangoproject.com', icon: '🐍', startYear: 2005 },
  { id: 'rubyonrails', name: 'Ruby on Rails', url: 'rubyonrails.org', icon: '💎', startYear: 2004 },
  { id: 'laravel', name: 'Laravel', url: 'laravel.com', icon: ' artisan', startYear: 2011 },
  { id: 'spring', name: 'Spring', url: 'spring.io', icon: '🍃', startYear: 2002 },
  { id: 'dotnet', name: '.NET', url: 'dotnet.microsoft.com', icon: '🌐', startYear: 2002 },
  { id: 'php', name: 'PHP', url: 'php.net', icon: '🐘', startYear: 1995 },
  { id: 'python', name: 'Python', url: 'python.org', icon: '🐍', startYear: 1995 },
  { id: 'java', name: 'Java', url: 'java.com', icon: '☕', startYear: 1995 },
  { id: 'cpp', name: 'C++', url: 'cplusplus.com', icon: '💻', startYear: 1995 },
  { id: 'swift', name: 'Swift', url: 'swift.org', icon: '🍎', startYear: 2014 },
  { id: 'kotlin', name: 'Kotlin', url: 'kotlinlang.org', icon: '⚙️', startYear: 2011 },
  { id: 'typescript', name: 'TypeScript', url: 'typescriptlang.org', icon: '🟦', startYear: 2012 },
  { id: 'golang', name: 'Go', url: 'go.dev', icon: '🐹', startYear: 2009 },
  { id: 'rustlang', name: 'Rust', url: 'rust-lang.org', icon: '🦀', startYear: 2010 },
  { id: 'haskell', name: 'Haskell', url: 'haskell.org', icon: 'λ', startYear: 1995 },
  { id: 'scala', name: 'Scala', url: 'scala-lang.org', icon: '📈', startYear: 2003 },
  { id: 'rstats', name: 'R', url: 'r-project.org', icon: '📊', startYear: 1995 },
  { id: 'matlab', name: 'MATLAB', url: 'mathworks.com/products/matlab', icon: '📉', startYear: 1995 },
  { id: 'jupyter', name: 'Jupyter', url: 'jupyter.org', icon: '💡', startYear: 2014 },
  { id: 'tensorflow', name: 'TensorFlow', url: 'tensorflow.org', icon: '🧠', startYear: 2015 },
  { id: 'pytorch', name: 'PyTorch', url: 'pytorch.org', icon: '💡', startYear: 2016 },
  { id: 'keras', name: 'Keras', url: 'keras.io', icon: '🧠', startYear: 2015 },
  { id: 'scikitlearn', name: 'Scikit-learn', url: 'scikit-learn.org', icon: '📊', startYear: 2007 },
  { id: 'pandas', name: 'Pandas', url: 'pandas.pydata.org', icon: '🐼', startYear: 2008 },
  { id: 'numpy', name: 'NumPy', url: 'numpy.org', icon: '🔢', startYear: 1995 },
  { id: 'docker', name: 'Docker', url: 'docker.com', icon: '🐳', startYear: 2013 },
  { id: 'kubernetes', name: 'Kubernetes', url: 'kubernetes.io', icon: '☸️', startYear: 2014 },
  { id: 'aws', name: 'AWS', url: 'aws.amazon.com', icon: '☁️', startYear: 2006 },
  { id: 'azure', name: 'Azure', url: 'azure.microsoft.com', icon: '☁️', startYear: 2010 },
  { id: 'gcp', name: 'Google Cloud', url: 'cloud.google.com', icon: '☁️', startYear: 2008 },
  { id: 'heroku', name: 'Heroku', url: 'heroku.com', icon: '☁️', startYear: 2007 },
  { id: 'netlify', name: 'Netlify', url: 'netlify.com', icon: '🌐', startYear: 2014 },
  { id: 'vercel', name: 'Vercel', url: 'vercel.com', icon: '▲', startYear: 2015 },
  { id: 'cloudflare', name: 'Cloudflare', url: 'cloudflare.com', icon: '☁️', startYear: 2009 },
  { id: 'githubpages', name: 'GitHub Pages', url: 'pages.github.com', icon: '🐙', startYear: 2008 },
  { id: 'gitlab', name: 'GitLab', url: 'gitlab.com', icon: '🦊', startYear: 2011 },
  { id: 'bitbucket', name: 'Bitbucket', url: 'bitbucket.org', icon: '‍', startYear: 2008 },
  { id: 'stackoverflowmeta', name: 'Stack Overflow Meta', url: 'meta.stackoverflow.com', icon: '📚', startYear: 2008 },
  { id: 'serverfault', name: 'Server Fault', url: 'serverfault.com', icon: '💻', startYear: 2009 },
  { id: 'superuser', name: 'Super User', url: 'superuser.com', icon: '💻', startYear: 2009 },
  { id: 'askubuntu', name: 'Ask Ubuntu', url: 'askubuntu.com', icon: '🐧', startYear: 2010 },
  { id: 'appledeveloper', name: 'Apple Developer', url: 'developer.apple.com', icon: '🍎', startYear: 1995 },
  { id: 'androiddeveloper', name: 'Android Developers', url: 'developer.android.com', icon: '🤖', startYear: 2007 },
  { id: 'mozilla', name: 'Mozilla', url: 'mozilla.org', icon: '🦊', startYear: 1998 },
  { id: 'w3c', name: 'W3C', url: 'w3.org', icon: '🌐', startYear: 1995 },
  { id: 'smashingmagazine', name: 'Smashing Magazine', url: 'smashingmagazine.com', icon: '📖', startYear: 2006 },
  { id: 'css-tricks', name: 'CSS-Tricks', url: 'css-tricks.com', icon: '🎨', startYear: 2007 },
  { id: 'sitepoint', name: 'SitePoint', url: 'sitepoint.com', icon: '📚', startYear: 1999 },
  { id: 'freecodecamp', name: 'freeCodeCamp', url: 'freecodecamp.org', icon: '🏕️', startYear: 2014 },
  { id: 'udemy', name: 'Udemy', url: 'udemy.com', icon: '🎓', startYear: 2010 },
  { id: 'coursera', name: 'Coursera', url: 'coursera.org', icon: '🎓', startYear: 2012 },
  { id: 'edx', name: 'edX', url: 'edx.org', icon: '🎓', startYear: 2012 },
  { id: 'khanacademy', name: 'Khan Academy', url: 'khanacademy.org', icon: '🏫', startYear: 2008 },
  { id: 'mediumblog', name: 'Medium Blog', url: 'blog.medium.com', icon: '📖', startYear: 2012 },
  { id: 'devto', name: 'DEV Community', url: 'dev.to', icon: '📝', startYear: 2016 },
  { id: 'hashnode', name: 'Hashnode', url: 'hashnode.com', icon: '📝', startYear: 2020 },
  { id: 'scotch_io', name: 'Scotch.io', url: 'scotch.io', icon: '🥃', startYear: 2013 },
  { id: 'tutorialspoint', name: 'TutorialsPoint', url: 'tutorialspoint.com', icon: '📚', startYear: 2006 },
  { id: 'geeksforgeeks', name: 'GeeksforGeeks', url: 'geeksforgeeks.org', icon: '🤓', startYear: 2007 },
  { id: 'programiz', name: 'Programiz', url: 'programiz.com', icon: '💻', startYear: 2012 },
  { id: 'codecademy', name: 'Codecademy', url: 'codecademy.com', icon: '🎓', startYear: 2011 },
  { id: 'hackerrank', name: 'HackerRank', url: 'hackerrank.com', icon: '💻', startYear: 2009 },
  { id: 'leetcode', name: 'LeetCode', url: 'leetcode.com', icon: '💻', startYear: 2011 },
  { id: 'topcoder', name: 'TopCoder', url: 'topcoder.com', icon: '🏆', startYear: 2001 },
  { id: 'codechef', name: 'CodeChef', url: 'codechef.com', icon: '👨‍🍳', startYear: 2009 },
  { id: 'codesignal', name: 'CodeSignal', url: 'codesignal.com', icon: '🚦', startYear: 2010 },
  { id: 'codewars', name: 'Codewars', url: 'codewars.com', icon: '🥋', startYear: 2012 },
  { id: 'projecteuler', name: 'Project Euler', url: 'projecteuler.net', icon: '🔢', startYear: 2001 },
  { id: 'kaggle', name: 'Kaggle', url: 'kaggle.com', icon: '📊', startYear: 2010 },
  { id: 'towardsdatascience', name: 'Towards Data Science', url: 'towardsdatascience.com', icon: '📈', startYear: 2016 },
  { id: 'reuters', name: 'Reuters', url: 'reuters.com', icon: '📰', startYear: 1995 },
  { id: 'bbc', name: 'BBC News', url: 'bbc.com/news', icon: '📰', startYear: 1997 },
  { id: 'cnn', name: 'CNN', url: 'cnn.com', icon: '📰', startYear: 1995 },
  { id: 'foxnews', name: 'Fox News', url: 'foxnews.com', icon: '📰', startYear: 1996 },
  { id: 'theguardian', name: 'The Guardian', url: 'theguardian.com', icon: '📰', startYear: 1995 },
  { id: 'wsj', name: 'Wall Street Journal', url: 'wsj.com', icon: '📰', startYear: 1995 },
  { id: 'bloomberg', name: 'Bloomberg', url: 'bloomberg.com', icon: '📈', startYear: 1995 },
  { id: 'forbes', name: 'Forbes', url: 'forbes.com', icon: '💰', startYear: 1995 },
  { id: 'businessinsider', name: 'Business Insider', url: 'businessinsider.com', icon: '💼', startYear: 2007 },
  { id: 'techradar', name: 'TechRadar', url: 'techradar.com', icon: '📱', startYear: 2008 },
  { id: 'zdnet', name: 'ZDNet', url: 'zdnet.com', icon: '💻', startYear: 1995 },
  { id: 'cnet', name: 'CNET', url: 'cnet.com', icon: '📱', startYear: 1995 },
  { id: 'gamespot', name: 'GameSpot', url: 'gamespot.com', icon: '🎮', startYear: 1996 },
  { id: 'ignentertainment', name: 'IGN', url: 'ign.com', icon: '🎮', startYear: 1996 },
  { id: 'polygon', name: 'Polygon', url: 'polygon.com', icon: '🎮', startYear: 2012 },
  { id: 'destructoid', name: 'Destructoid', url: 'destructoid.com', icon: '🎮', startYear: 2006 },
  { id: 'rottentomatoesmovies', name: 'Rotten Tomatoes', url: 'rottentomatoes.com', icon: '🍅', startYear: 1998 },
  { id: 'metacritic', name: 'Metacritic', url: 'metacritic.com', icon: '📊', startYear: 1999 },
  { id: 'allmusic', name: 'AllMusic', url: 'allmusic.com', icon: '🎶', startYear: 1995 },
  { id: 'discogs', name: 'Discogs', url: 'discogs.com', icon: '💿', startYear: 2000 },
  { id: 'lastfm', name: 'Last.fm', url: 'last.fm', icon: '🎶', startYear: 2002 },
  { id: 'bandcamp', name: 'Bandcamp', url: 'bandcamp.com', icon: '🎶', startYear: 2008 },
  { id: 'soundcloud', name: 'SoundCloud', url: 'soundcloud.com', icon: '🔊', startYear: 2007 },
  { id: 'mixcloud', name: 'Mixcloud', url: 'mixcloud.com', icon: '🎧', startYear: 2008 },
  { id: 'deezer', name: 'Deezer', url: 'deezer.com', icon: '🎧', startYear: 2007 },
  { id: 'tidal', name: 'Tidal', url: 'tidal.com', icon: '🌊', startYear: 2014 },
  { id: 'spotifyweb', name: 'Spotify Web Player', url: 'open.spotify.com', icon: '🎧', startYear: 2006 },
  { id: 'apple_music', name: 'Apple Music', url: 'music.apple.com', icon: '🍎', startYear: 2015 },
  { id: 'youtube_music', name: 'YouTube Music', url: 'music.youtube.com', icon: '📺', startYear: 2015 },
  { id: 'pandora', name: 'Pandora', url: 'pandora.com', icon: '🎶', startYear: 2000 },
  { id: 'iheartradio', name: 'iHeartRadio', url: 'iheart.com', icon: '📻', startYear: 2008 },
  { id: 'siriusxm', name: 'SiriusXM', url: 'siriusxm.com', icon: '📻', startYear: 2002 },
  { id: 'audible', name: 'Audible', url: 'audible.com', icon: '🎧', startYear: 1995 },
  { id: 'goodreads', name: 'Goodreads', url: 'goodreads.com', icon: '📚', startYear: 2007 },
  { id: 'wattpad', name: 'Wattpad', url: 'wattpad.com', icon: '📖', startYear: 2006 },
  { id: 'fanfiction', name: 'FanFiction.Net', url: 'fanfiction.net', icon: '📝', startYear: 1998 },
  { id: 'archiveofourown', name: 'Archive of Our Own', url: 'archiveofourown.org', icon: '📚', startYear: 2008 },
  { id: 'deviantartart', name: 'DeviantArt', url: 'deviantart.com', icon: '🎨', startYear: 2000 },
  { id: 'artstation', name: 'ArtStation', url: 'artstation.com', icon: '🎨', startYear: 2014 },
  { id: 'behanceportfolio', name: 'Behance', url: 'behance.net', icon: '🖌️', startYear: 2006 },
  { id: 'dribbbledesign', name: 'Dribbble', url: 'dribbble.com', icon: '🏀', startYear: 2009 },
  { id: 'flickrphoto', name: 'Flickr', url: 'flickr.com', icon: '📸', startYear: 2004 },
  { id: '500px', name: '500px', url: '500px.com', icon: '📸', startYear: 2007 },
  { id: 'vimeo', name: 'Vimeo', url: 'vimeo.com', icon: '🎬', startYear: 2004 },
  { id: 'dailymotion', name: 'Dailymotion', url: 'dailymotion.com', icon: '🎬', startYear: 2005 },
  { id: 'twitchstream', name: 'Twitch', url: 'twitch.tv', icon: '🎮', startYear: 2011 },
  { id: 'patreon', name: 'Patreon', url: 'patreon.com', icon: '💰', startYear: 2013 },
  { id: 'ko-fi', name: 'Ko-fi', url: 'ko-fi.com', icon: '☕', startYear: 2013 },
  { id: 'buy_me_a_coffee', name: 'Buy Me a Coffee', url: 'buymeacoffee.com', icon: '☕', startYear: 2017 },
  { id: 'substack', name: 'Substack', url: 'substack.com', icon: '📰', startYear: 2017 },
  { id: 'mediumblogging', name: 'Medium', url: 'medium.com', icon: '📖', startYear: 2012 },
  { id: 'hashnodeblog', name: 'Hashnode', url: 'hashnode.com', icon: '📝', startYear: 2020 },
  { id: 'devto_blog', name: 'DEV Community', url: 'dev.to', icon: '📝', startYear: 2016 },
  { id: 'indiegogo', name: 'Indiegogo', url: 'indiegogo.com', icon: '💡', startYear: 2008 },
  { id: 'kickstarter', name: 'Kickstarter', url: 'kickstarter.com', icon: '🚀', startYear: 2009 },
  { id: 'gofundme', name: 'GoFundMe', url: 'gofundme.com', icon: '❤️', startYear: 2010 },
  { id: 'changeorg', name: 'Change.org', url: 'change.org', icon: '✊', startYear: 2007 },
  { id: 'avast', name: 'Avast', url: 'avast.com', icon: '🛡️', startYear: 1995 },
  { id: 'avg', name: 'AVG', url: 'avg.com', icon: '🛡️', startYear: 1995 },
  { id: 'malwarebytes', name: 'Malwarebytes', url: 'malwarebytes.com', icon: '🛡️', startYear: 2008 },
  { id: 'norton', name: 'Norton', url: 'norton.com', icon: '🛡️', startYear: 1995 },
  { id: 'mcafee', name: 'McAfee', url: 'mcafee.com', icon: '🛡️', startYear: 1995 },
  { id: 'kaspersky', name: 'Kaspersky', url: 'kaspersky.com', icon: '🛡️', startYear: 1997 },
  { id: 'eset', name: 'ESET', url: 'eset.com', icon: '🛡️', startYear: 1995 },
  { id: 'bitdefender', name: 'Bitdefender', url: 'bitdefender.com', icon: '🛡️', startYear: 2001 },
  { id: 'lastpass', name: 'LastPass', url: 'lastpass.com', icon: '🔑', startYear: 2008 },
  { id: '1password', name: '1Password', url: '1password.com', icon: '🔑', startYear: 2008 },
  { id: 'dashlane', name: 'Dashlane', url: 'dashlane.com', icon: '🔑', startYear: 2009 },
  { id: 'protonmail', name: 'ProtonMail', url: 'proton.me/mail', icon: '✉️', startYear: 2014 },
  { id: 'tutanota', name: 'Tutanota', url: 'tutanota.com', icon: '✉️', startYear: 2014 },
  { id: 'signal', name: 'Signal', url: 'signal.org', icon: '💬', startYear: 2014 },
  { id: 'telegram', name: 'Telegram', url: 'telegram.org', icon: '💬', startYear: 2013 },
  { id: 'threema', name: 'Threema', url: 'threema.ch', icon: '💬', startYear: 2012 },
  { id: 'discordapp', name: 'Discord', url: 'discord.com', icon: '🔊', startYear: 2015 },
  { id: 'slackapp', name: 'Slack', url: 'slack.com', icon: '🗨️', startYear: 2013 },
  { id: 'microsoftteams', name: 'Microsoft Teams', url: 'microsoft.com/en-us/microsoft-teams', icon: '🤝', startYear: 2017 },
  { id: 'zoomvideo', name: 'Zoom', url: 'zoom.us', icon: '📞', startYear: 2011 },
  { id: 'googlemeet', name: 'Google Meet', url: 'meet.google.com', icon: '📞', startYear: 2017 },
  { id: 'skypevideo', name: 'Skype', url: 'skype.com', icon: '💬', startYear: 2003 },
  { id: 'webexmeetings', name: 'Webex', url: 'webex.com', icon: '💻', startYear: 1995 },
  { id: 'gotomeeting', name: 'GoToMeeting', url: 'gotomeeting.com', icon: '📞', startYear: 2004 },
  { id: 'calendly', name: 'Calendly', url: 'calendly.com', icon: '📅', startYear: 2013 },
  { id: 'doodle', name: 'Doodle', url: 'doodle.com', icon: '📅', startYear: 2003 },
  { id: 'bookingcom', name: 'Booking.com', url: 'booking.com', icon: '🏨', startYear: 1996 },
  { id: 'expedia', name: 'Expedia', url: 'expedia.com', icon: '✈️', startYear: 1996 },
  { id: 'kayak', name: 'Kayak', url: 'kayak.com', icon: '✈️', startYear: 2004 },
  { id: 'tripadvisor', name: 'TripAdvisor', url: 'tripadvisor.com', icon: '🗺️', startYear: 2000 },
  { id: 'airbnb', name: 'Airbnb', url: 'airbnb.com', icon: '🏠', startYear: 2008 },
  { id: 'vrbo', name: 'Vrbo', url: 'vrbo.com', icon: '🏡', startYear: 1995 },
  { id: 'hotelscom', name: 'Hotels.com', url: 'hotels.com', icon: '🏨', startYear: 1995 },
  { id: 'trivago', name: 'Trivago', url: 'trivago.com', icon: '🏨', startYear: 2005 },
  { id: 'priceline', name: 'Priceline', url: 'priceline.com', icon: '💰', startYear: 1997 },
  { id: 'southwest', name: 'Southwest Airlines', url: 'southwest.com', icon: '✈️', startYear: 1995 },
  { id: 'delta', name: 'Delta Airlines', url: 'delta.com', icon: '✈️', startYear: 1995 },
  { id: 'united', name: 'United Airlines', url: 'united.com', icon: '✈️', startYear: 1995 },
  { id: 'americanairlines', name: 'American Airlines', url: 'aa.com', icon: '✈️', startYear: 1995 },
  { id: 'emirates', name: 'Emirates', url: 'emirates.com', icon: '✈️', startYear: 1995 },
  { id: 'qatarairways', name: 'Qatar Airways', url: 'qatarairways.com', icon: '✈️', startYear: 1997 },
  { id: 'singaporeair', name: 'Singapore Airlines', url: 'singaporeair.com', icon: '✈️', startYear: 1995 },
  { id: 'lufthansa', name: 'Lufthansa', url: 'lufthansa.com', icon: '✈️', startYear: 1995 },
  { id: 'airfrance', name: 'Air France', url: 'airfrance.com', icon: '✈️', startYear: 1995 },
  { id: 'britishairways', name: 'British Airways', url: 'britishairways.com', icon: '✈️', startYear: 1995 },
  { id: 'klm', name: 'KLM', url: 'klm.com', icon: '✈️', startYear: 1995 },
  { id: 'alitalia', name: 'Alitalia', url: 'alitalia.com', icon: '✈️', startYear: 1995 },
  { id: 'iberia', name: 'Iberia', url: 'iberia.com', icon: '✈️', startYear: 1995 },
  { id: 'latam', name: 'LATAM Airlines', url: 'latam.com', icon: '✈️', startYear: 2012 },
  { id: 'copaair', name: 'Copa Airlines', url: 'copaair.com', icon: '✈️', startYear: 1995 },
  { id: 'aeromexico', name: 'Aeromexico', url: 'aeromexico.com', icon: '✈️', startYear: 1995 },
  { id: 'volaris', name: 'Volaris', url: 'volaris.com', icon: '✈️', startYear: 2006 },
  { id: 'interjet', name: 'Interjet', url: 'interjet.com.mx', icon: '✈️', startYear: 2005 },
  { id: 'jetblue', name: 'JetBlue', url: 'jetblue.com', icon: '✈️', startYear: 1999 },
  { id: 'frontier', name: 'Frontier Airlines', url: 'flyfrontier.com', icon: '✈️', startYear: 1995 },
  { id: 'spirit', name: 'Spirit Airlines', url: 'spirit.com', icon: '✈️', startYear: 1995 },
  { id: 'allegiant', name: 'Allegiant Air', url: 'allegiantair.com', icon: '✈️', startYear: 1997 },
  { id: 'ryanair', name: 'Ryanair', url: 'ryanair.com', icon: '✈️', startYear: 1995 },
  { id: 'easyjet', name: 'easyJet', url: 'easyjet.com', icon: '✈️', startYear: 1995 },
  { id: 'norwegian', name: 'Norwegian Air Shuttle', url: 'norwegian.com', icon: '✈️', startYear: 1995 },
  { id: 'wizzair', name: 'Wizz Air', url: 'wizzair.com', icon: '✈️', startYear: 2003 },
  { id: 'airasia', name: 'AirAsia', url: 'airasia.com', icon: '✈️', startYear: 1995 },
  { id: 'lionair', name: 'Lion Air', url: 'lionair.co.id', icon: '✈️', startYear: 1999 },
  { id: 'garudaindonesia', name: 'Garuda Indonesia', url: 'garuda-indonesia.com', icon: '✈️', startYear: 1995 },
  { id: 'thaiairways', name: 'Thai Airways', url: 'thaiairways.com', icon: '✈️', startYear: 1995 },
  { id: 'vietjetair', name: 'Vietjet Air', url: 'vietjetair.com', icon: '✈️', startYear: 2007 },
  { id: 'cebupacificair', name: 'Cebu Pacific Air', url: 'cebupacificair.com', icon: '✈️', startYear: 1996 },
  { id: 'koreanair', name: 'Korean Air', url: 'koreanair.com', icon: '✈️', startYear: 1995 },
  { id: 'asianaairlines', name: 'Asiana Airlines', url: 'flyasiana.com', icon: '✈️', startYear: 1995 },
  { id: 'chinaeastern', name: 'China Eastern Airlines', url: 'chinaeasternairlines.com', icon: '✈️', startYear: 1995 },
  { id: 'chinasouthern', name: 'China Southern Airlines', url: 'chinasouthern.com', icon: '✈️', startYear: 1995 },
  { id: 'airchina', name: 'Air China', url: 'airchina.com', icon: '✈️', startYear: 1995 },
  { id: 'cathaypacific', name: 'Cathay Pacific', url: 'cathaypacific.com', icon: '✈️', startYear: 1995 },
  { id: 'evaair', name: 'EVA Air', url: 'evaair.com', icon: '✈️', startYear: 1995 },
  { id: 'ana', name: 'All Nippon Airways', url: 'ana.co.jp', icon: '✈️', startYear: 1995 },
  { id: 'jal', name: 'Japan Airlines', url: 'jal.com', icon: '✈️', startYear: 1995 },
  { id: 'malaysiaairlines', name: 'Malaysia Airlines', url: 'malaysiaairlines.com', icon: '✈️', startYear: 1995 },
  { id: 'garuda', name: 'Garuda Indonesia', url: 'garuda-indonesia.com', icon: '✈️', startYear: 1995 },
  { id: 'turkishairlines', name: 'Turkish Airlines', url: 'turkishairlines.com', icon: '✈️', startYear: 1995 },
  { id: 'egyptair', name: 'EgyptAir', url: 'egyptair.com', icon: '✈️', startYear: 1995 },
  { id: 'ethiopianairlines', name: 'Ethiopian Airlines', url: 'ethiopianairlines.com', icon: '✈️', startYear: 1995 },
  { id: 'southafricanairways', name: 'South African Airways', url: 'flysaa.com', icon: '✈️', startYear: 1995 },
  { id: 'kenyaairways', name: 'Kenya Airways', url: 'kenya-airways.com', icon: '✈️', startYear: 1995 },
  { id: 'royalairmaroc', name: 'Royal Air Maroc', url: 'royalairmaroc.com', icon: '✈️', startYear: 1995 },
  { id: 'saudia', name: 'Saudia', url: 'saudia.com', icon: '✈️', startYear: 1995 },
  { id: 'elal', name: 'El Al', url: 'elal.com', icon: '✈️', startYear: 1995 },
  { id: 'swiss', name: 'SWISS', url: 'swiss.com', icon: '✈️', startYear: 1995 },
  { id: 'austrian', name: 'Austrian Airlines', url: 'austrian.com', icon: '✈️', startYear: 1995 },
  { id: 'sas', name: 'SAS', url: 'flysas.com', icon: '✈️', startYear: 1995 },
  { id: 'finnair', name: 'Finnair', url: 'finnair.com', icon: '✈️', startYear: 1995 },
  { id: 'aeroflot', name: 'Aeroflot', url: 'aeroflot.ru', icon: '✈️', startYear: 1995 },
  { id: 's7airlines', name: 'S7 Airlines', url: 's7.ru', icon: '✈️', startYear: 1995 },
  { id: 'uralairlines', name: 'Ural Airlines', url: 'uralairlines.ru', icon: '✈️', startYear: 1995 },
  { id: 'azurair', name: 'Azur Air', url: 'azurair.com', icon: '✈️', startYear: 2014 },
  { id: 'nordwindairlines', name: 'Nordwind Airlines', url: 'nordwindairlines.ru', icon: '✈️', startYear: 2008 },
  { id: 'pobeda', name: 'Pobeda Airlines', url: 'pobeda.aero', icon: '✈️', startYear: 2014 },
  { id: 'rossiya', name: 'Rossiya Airlines', url: 'rossiya-airlines.com', icon: '✈️', startYear: 1995 },
  { id: 'aircanada', name: 'Air Canada', url: 'aircanada.com', icon: '✈️', startYear: 1995 },
  { id: 'westjet', name: 'WestJet', url: 'westjet.com', icon: '✈️', startYear: 1996 },
  { id: 'airtransat', name: 'Air Transat', url: 'airtransat.com', icon: '✈️', startYear: 1995 },
  { id: 'porterairlines', name: 'Porter Airlines', url: 'flyporter.com', icon: '✈️', startYear: 2006 },
  { id: 'sunwingairlines', name: 'Sunwing Airlines', url: 'sunwing.ca', icon: '✈️', startYear: 2001 },
  { id: 'aerlingus', name: 'Aer Lingus', url: 'aerlingus.com', icon: '✈️', startYear: 1995 },
  { id: 'icelandair', name: 'Icelandair', url: 'icelandair.com', icon: '✈️', startYear: 1995 },
  { id: 'norwegianair', name: 'Norwegian', url: 'norwegian.com', icon: '✈️', startYear: 1995 },
  { id: 'scoot', name: 'Scoot', url: 'flyscoot.com', icon: '✈️', startYear: 2011 },
  { id: 'peachaviation', name: 'Peach Aviation', url: 'flypeach.com', icon: '✈️', startYear: 2011 },
  { id: 'jetstar', name: 'Jetstar', url: 'jetstar.com', icon: '✈️', startYear: 2003 },
  { id: 'virginatlantic', name: 'Virgin Atlantic', url: 'virginatlantic.com', icon: '✈️', startYear: 1995 },
  { id: 'airnewzealand', name: 'Air New Zealand', url: 'airnewzealand.com', icon: '✈️', startYear: 1995 },
  { id: 'qantas', name: 'Qantas', url: 'qantas.com', icon: '✈️', startYear: 1995 },
  { id: 'virginaustralia', name: 'Virgin Australia', url: 'virginaustralia.com', icon: '✈️', startYear: 2000 },
];
